[package]
name = "rustic_testing"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
aho-corasick = { workspace = true }
anyhow = { workspace = true }
bytes = { workspace = true }
enum-map = { workspace = true }
once_cell = "1.19.0"
parking_lot = { workspace = true }
rustic_core = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
